# Generated by Django 2.2.7 on 2020-11-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='recipe',
        ),
    ]
