# Generated by Django 2.2.7 on 2020-11-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
