# Generated by Django 2.2.7 on 2020-11-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='metrics',
            field=models.CharField(choices=[('US', 'USA'), ('EU', 'EU'), ('UK', 'UK')], default='EU', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
