# Generated by Django 2.2.7 on 2020-11-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201118_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='metrics',
            field=models.CharField(choices=[('US', 'USA'), ('EU', 'EU'), ('UK', 'UK')], default='EU', max_length=2),
        ),
    ]
