# Generated by Django 2.2.7 on 2020-11-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20201119_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='meals_per_day',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1),
        ),
    ]
