# Generated by Django 2.2.7 on 2020-11-19 11:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20201119_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allergens',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Allergen 1'), ('2', 'Allergen 2'), ('3', 'Allergen 3'), ('4', 'Allergen 4'), ('5', 'Allergen 5')], max_length=10),
        ),
    ]
