# Generated by Django 2.2.7 on 2020-11-19 21:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20201119_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='medical_conditions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'AIDS'), ('2', 'Hearth Health'), ('3', 'Kidney Disease'), ('4', 'Diabetes'), ('5', 'Cancer'), ('6', 'Lupus')], max_length=14),
        ),
    ]
