# Generated by Django 2.2.7 on 2020-11-19 22:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_userprofile_medical_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='risk_factors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Weight loss within 3 months'), ('2', 'Reduced dietary intake in the last week'), ('3', 'ICU patient')], max_length=14),
        ),
    ]
