# Generated by Django 2.2.7 on 2020-11-20 21:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20201120_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allergens',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allergen-1', 'Allergen 1'), ('allergen-2', 'Allergen 2'), ('allergen-3', 'Allergen 3'), ('allergen-4', 'Allergen 4'), ('allergen-5', 'Allergen 5')], max_length=100),
        ),
    ]
