# Generated by Django 2.2.7 on 2020-11-21 13:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20201120_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allergens',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allergen-1', 'Allergen 1'), ('allergen-2', 'Allergen 2'), ('allergen-3', 'Allergen 3'), ('allergen-4', 'Allergen 4'), ('allergen-5', 'Allergen 5')], max_length=120, verbose_name='allergens'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medical_conditions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('aids', 'AIDS'), ('hearth-health', 'Hearth Health'), ('kidney-disease', 'Kidney Disease'), ('diabetes', 'Diabetes'), ('cancer', 'Cancer'), ('lupus', 'Lupus')], max_length=120, verbose_name='medical_conditions'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='risk_factors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('weight-loss-within-3-months', 'Weight loss within 3 months'), ('reduced-dietary-intake-in-the-last-week', 'Reduced dietary intake in the last week'), ('icu-patient', 'ICU patient')], max_length=120, verbose_name='risk_factors'),
        ),
    ]
