# Generated by Django 2.2.7 on 2020-11-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20201121_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='meals_per_day',
            field=models.CharField(choices=[('1', '1 meal'), ('2', '2 meals'), ('3', '3 meals'), ('4', '4 meals'), ('5', '5 meals')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=7),
        ),
    ]
