# Generated by Django 2.2.7 on 2020-11-22 12:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20201122_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='medical_conditions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('aids', 'AIDS'), ('hearth-health', 'Hearth Health'), ('kidney-disease', 'Kidney Disease'), ('diabetes', 'Diabetes'), ('cancer', 'Cancer'), ('lupus', 'Lupus')], max_length=120, verbose_name='medical_conditions'),
        ),
    ]
