# Generated by Django 2.2.7 on 2020-11-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20201122_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.CharField(blank=True, choices=[('Group 1', (('aids', 'AIDS'), ('hearth-health', 'Hearth Health'), ('kidney-disease', 'Kidney Disease'))), ('Group 2', (('diabetes', 'Diabetes'), ('cancer', 'Cancer'), ('lupus', 'Lupus')))], max_length=1000, verbose_name='medical_conditions'),
        ),
    ]
