# Generated by Django 2.2.7 on 2020-11-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20201122_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.CharField(blank=True, choices=[('aids', 'AIDS'), ('hearth-health', 'Hearth Health'), ('kidney-disease', 'Kidney Disease'), ('diabetes', 'Diabetes'), ('cancer', 'Cancer'), ('lupus', 'Lupus')], max_length=240, verbose_name='medical_conditions'),
        ),
    ]
