# Generated by Django 2.2.7 on 2020-11-23 10:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20201123_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='medical_conditions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Group 1', ((1, 'AIDS'), (2, 'Hearth Health'), (3, 'Kidney Disease'))), ('Group 2', ((4, 'Diabetes'), (5, 'Cancer'), (6, 'Lupus')))], max_length=240, verbose_name='medical_conditions'),
        ),
    ]
