# Generated by Django 2.2.7 on 2020-11-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20201123_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='metrics',
            field=models.CharField(choices=[('1', 'Imperial'), ('2', 'Metric')], default='EU', max_length=1),
        ),
    ]
