# Generated by Django 2.2.7 on 2020-11-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20201123_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='metrics',
            new_name='units',
        ),
    ]
