# Generated by Django 2.2.7 on 2020-12-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalconditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalconditions',
            options={'verbose_name': 'Medical Condition', 'verbose_name_plural': 'Medical Conditions'},
        ),
        migrations.AlterModelOptions(
            name='medicalconditionsgroup',
            options={'verbose_name': 'Medical Conditions Group', 'verbose_name_plural': 'Medical Conditions Groups'},
        ),
    ]
