# Generated by Django 2.2.7 on 2020-12-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalconditions', '0002_auto_20201223_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalConditions',
        ),
        migrations.DeleteModel(
            name='MedicalConditionsGroup',
        ),
    ]
