# Generated by Django 2.2.7 on 2020-12-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicalconditions', '0003_auto_20201223_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalConditionsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Medical Conditions Group',
                'verbose_name_plural': 'Medical Conditions Groups',
            },
        ),
        migrations.CreateModel(
            name='MedicalConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalconditions.MedicalConditionsGroup')),
            ],
            options={
                'verbose_name': 'Medical Condition',
                'verbose_name_plural': 'Medical Conditions',
            },
        ),
    ]
