# Generated by Django 2.2.7 on 2020-12-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalconditions', '0004_medicalconditions_medicalconditionsgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalconditionsgroup',
            options={'verbose_name': 'Medical Condition Group', 'verbose_name_plural': 'Medical Conditions Groups'},
        ),
    ]
