# Generated by Django 2.2.7 on 2020-12-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalconditions', '0005_auto_20201223_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalconditionsgroup',
            options={'verbose_name': 'Medical Condition Group', 'verbose_name_plural': 'Medical Condition Groups'},
        ),
    ]
