# Generated by Django 2.2.7 on 2020-12-08 08:35

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPreparationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('description', models.TextField(verbose_name='Content')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='foodpreparationtypes.FoodPreparationType')),
            ],
            options={
                'verbose_name': 'Food Preparation Type',
                'verbose_name_plural': 'Food Preparation Types',
                'unique_together': {('parent', 'slug')},
            },
        ),
    ]
