# Generated by Django 2.2.7 on 2020-12-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodpreparationtypes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpreparationtype',
            name='description',
        ),
    ]
