# Generated by Django 2.2.7 on 2020-12-08 08:47

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foodpreparationtypes', '0002_remove_foodpreparationtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpreparationtype',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='foodpreparationtypes.Foodpreparationtype'),
        ),
    ]
