# Generated by Django 2.2.7 on 2020-12-08 08:51

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foodpreparationtypes', '0003_auto_20201208_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodpreparationtype',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='foodpreparationtype',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='foodpreparationtypes.Foodpreparationtype'),
        ),
        migrations.AlterUniqueTogether(
            name='foodpreparationtype',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='foodpreparationtype',
            name='slug',
        ),
    ]
