# Generated by Django 2.2.7 on 2020-12-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodpreparationtypes', '0010_auto_20201223_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPreparationTypeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='foodpreparationtype',
            name='parent',
        ),
        migrations.AddField(
            model_name='foodpreparationtype',
            name='description',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='foodpreparationtype',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='foodpreparationtypes.FoodPreparationTypeCategory'),
        ),
    ]
