# Generated by Django 2.2.7 on 2020-12-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodpreparationtypes', '0011_auto_20201223_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpreparationtype',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=512),
        ),
    ]
