# Generated by Django 2.2.7 on 2020-12-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodpreparationtypes', '0012_auto_20201223_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodpreparationtypecategory',
            options={'verbose_name': 'Food Preparation Type Category', 'verbose_name_plural': 'Food Preparation Type Categories'},
        ),
    ]
