# Generated by Django 2.2.7 on 2020-12-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodpreparationtypes', '0013_auto_20201223_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpreparationtype',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=1024),
        ),
    ]
