# Generated by Django 2.2.7 on 2020-12-07 21:16

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrates',
            field=models.IntegerField(blank=True, help_text='Carbohydrades', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='energy',
            field=models.IntegerField(blank=True, help_text='Calories', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fats',
            field=models.IntegerField(blank=True, help_text='Fats', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fiber',
            field=models.IntegerField(blank=True, help_text='Fiber', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.IntegerField(blank=True, help_text='Protein', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='saturated_fatty_acids',
            field=models.IntegerField(blank=True, help_text='Saturated Fatty Acids', null=True, verbose_name='Saturated Fatty Acids'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sodium',
            field=models.IntegerField(blank=True, help_text='Sodium', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sugars',
            field=models.IntegerField(blank=True, help_text='Sugars', null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingredients.Category', verbose_name='Ingredient Types'),
        ),
    ]
