# Generated by Django 2.2.7 on 2020-12-07 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20201207_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Ingredient Type', 'verbose_name_plural': 'Ingredient Types'},
        ),
    ]
