# Generated by Django 2.2.7 on 2020-12-07 21:44

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20201207_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Carbohydrades (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingredients.Category'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='energy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Energy value (kcal)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fats (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fiber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fiber (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.IntegerField(blank=True, null=True, verbose_name='Protein (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='saturated_fatty_acids',
            field=models.IntegerField(blank=True, null=True, verbose_name='Saturated Fatty Acids (g)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sodium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sodium (mg)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sugars',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sugars (g)'),
        ),
    ]
