# Generated by Django 2.2.7 on 2020-12-07 21:48

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_auto_20201207_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingredients.Category', verbose_name='Ingredient Type'),
        ),
    ]
